;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Item.Cono",NewTagName="Item.Trofeongo1")
+GameplayTagRedirects=(OldTagName="Item.Esfera",NewTagName="Item.Trofeongo2")
+GameplayTagRedirects=(OldTagName="Item.Cubo",NewTagName="Item.Trofeongo3")
+GameplayTagRedirects=(OldTagName="State.Scene01",NewTagName="State.Gameplay01")
+GameplayTagRedirects=(OldTagName="State.Scene02",NewTagName="State.Gameplay02")
+GameplayTagRedirects=(OldTagName="Azul.Planeta.Planeta1",NewTagName="Azul.Planeta.Azul")
+GameplayTagRedirects=(OldTagName="Azul.Planeta.Planeta2",NewTagName="Azul.Planeta.Amarillo")
+GameplayTagRedirects=(OldTagName="Azul.Planeta.Planeta3",NewTagName="Azul.Planeta.Blanco")
+GameplayTagRedirects=(OldTagName="Azul.Planeta.Planeta4",NewTagName="Azul.Planeta.Verde")
+GameplayTagRedirects=(OldTagName="Azul.Planeta.Planeta5",NewTagName="Azul.Planeta.Rosa")
+GameplayTagList=(Tag="Azul.Piezas.Pieza1",DevComment="")
+GameplayTagList=(Tag="Azul.Piezas.Pieza2",DevComment="")
+GameplayTagList=(Tag="Azul.Piezas.Pieza3",DevComment="")
+GameplayTagList=(Tag="Azul.Piezas.Pieza4",DevComment="")
+GameplayTagList=(Tag="Azul.Piezas.Pieza5",DevComment="")
+GameplayTagList=(Tag="Azul.Piezas.Pieza6",DevComment="")
+GameplayTagList=(Tag="Azul.Planeta.Amarillo",DevComment="")
+GameplayTagList=(Tag="Azul.Planeta.Azul",DevComment="")
+GameplayTagList=(Tag="Azul.Planeta.Blanco",DevComment="")
+GameplayTagList=(Tag="Azul.Planeta.Rojo",DevComment="")
+GameplayTagList=(Tag="Azul.Planeta.Rosa",DevComment="")
+GameplayTagList=(Tag="Azul.Planeta.Verde",DevComment="")
+GameplayTagList=(Tag="Azul.Player.GrabbedObject",DevComment="")
+GameplayTagList=(Tag="Azul.Player.RotatingObject",DevComment="")
+GameplayTagList=(Tag="Azul.StoryObject.CanPickup",DevComment="")
+GameplayTagList=(Tag="DialogoNPC.Baul",DevComment="")
+GameplayTagList=(Tag="DialogoNPC.Cuna",DevComment="")
+GameplayTagList=(Tag="DialogoNPC.Son",DevComment="")
+GameplayTagList=(Tag="Gameplay.01",DevComment="")
+GameplayTagList=(Tag="Gameplay.02",DevComment="")
+GameplayTagList=(Tag="Gameplay.03",DevComment="")
+GameplayTagList=(Tag="Gameplay.04",DevComment="")
+GameplayTagList=(Tag="Gameplay.05",DevComment="")
+GameplayTagList=(Tag="Gameplay.06",DevComment="")
+GameplayTagList=(Tag="Gameplay.07",DevComment="")
+GameplayTagList=(Tag="Gameplay.08",DevComment="")
+GameplayTagList=(Tag="Gameplay.09",DevComment="")
+GameplayTagList=(Tag="Gameplay.10",DevComment="")
+GameplayTagList=(Tag="Gameplay.11",DevComment="")
+GameplayTagList=(Tag="Gameplay.12",DevComment="")
+GameplayTagList=(Tag="Item.Trofeongo1",DevComment="")
+GameplayTagList=(Tag="Item.Trofeongo2",DevComment="")
+GameplayTagList=(Tag="Item.Trofeongo3",DevComment="")
+GameplayTagList=(Tag="Tutorial.Completed",DevComment="")
+GameplayTagList=(Tag="Tutorial.First",DevComment="")
+GameplayTagList=(Tag="Tutorial.First.Look",DevComment="")
+GameplayTagList=(Tag="Tutorial.First.Move",DevComment="")
+GameplayTagList=(Tag="Tutorial.First.Move.A",DevComment="")
+GameplayTagList=(Tag="Tutorial.First.Move.D",DevComment="")
+GameplayTagList=(Tag="Tutorial.First.Move.S",DevComment="")
+GameplayTagList=(Tag="Tutorial.First.Move.W",DevComment="")
+GameplayTagList=(Tag="Tutorial.First.Space",DevComment="")
+GameplayTagList=(Tag="Tutorial.Interact",DevComment="")
+GameplayTagList=(Tag="Tutorial.OpenManual",DevComment="")
+GameplayTagList=(Tag="Tutorial.TakeManual",DevComment="")

